#! /bin/sh
# postrm script for cricket
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see /usr/doc/packaging-manual/

case "$1" in
    purge)

	if id cricket > /dev/null 2>&1; then
		userdel cricket
	else
		echo "Can't remove user cricket. Please remove this user by hand."
	fi

	if sg cricket -c true 2>/dev/null; then
		groupdel cricket
	else
		echo "Can't remove user cricket. Please remove this user by hand."
	fi

	rm -rf /etc/cricket /var/cache/cricket /var/lib/cricket \
	    /var/log/cricket

        ;;

    remove|upgrade|failed-upgrade|abort-install|disappear)
        ;;
        
    abort-upgrade)
        if dpkg --compare-versions "$2" lt "1.0.2+1.0.3-pre4b-1" && \
            test -d /etc/cricket/config
            then
            find /etc/cricket/config -maxdepth 1 -mindepth 1 -print0 | \
                xargs -0 --no-run-if-empty \
                mv --target-directory=/etc/cricket
        fi

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac

#DEBHELPER#
